---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# longcfa

<!-- badges: start -->
<!-- badges: end -->

The goal of longcfa is to ...

## Installation

You can install the development version of longcfa from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("marklhc/longcfa")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(longcfa)
library(lavaan)
# Indicator matrix
spec <- matrix(c(
    "y1", "y2", "y3", "y4",
    "y5", "y6", "y7", "y8"
), ncol = 2)
# Scalar invariance
fit <- longcfa(spec,
               lv_names = c("dem60", "dem65"),
               data = PoliticalDemocracy,
               long_equal = c("loadings", "intercepts"))
summary(fit)
# Partial invariance
fit2 <- longcfa(spec,
                lv_names = c("dem60", "dem65"),
                data = PoliticalDemocracy,
                long_equal = c("loadings", "intercepts"),
                long_partial = list(
                    loadings = matrix(c(1, 2), ncol = 2),
                    intercepts = matrix(c(1, 3, 2, 2), ncol = 2)
                ))
summary(fit2)
```
