---
title: "Standard Errors with Penalized Estimation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Standard Errors with Penalized Estimation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r}
library(longcfa)
library(lavaan)
library(plavaan)
data(PoliticalDemocracy)
```

## Penalize cross-loadings

### Two-factor CFA model

```{r}
mod0 <- "
  ind60 =~ x1 + x2 + x3
  dem60 =~ y1 + y2 + y3 + y4
  ind60 ~~ dem60
"
fit0 <- cfa(mod0, data = PoliticalDemocracy, std.lv = TRUE, estimator = "MLR")
```

```{r eval=FALSE, include=FALSE}
# lav_model_vcov_se(fit0@Model, fit0@ParTable)  # not what I expected
lavaan:::lav_model_nvcov_robust_sem
lavaan:::lav_model_nvcov_robust_sandwich
lavaan:::computeDelta(fit0@Model)
lavaan:::lav_model_information_firstorder(
    lavmodel = fit0@Model,
    lavsamplestats = fit0@SampleStats,
    lavdata = fit0@Data,
    lavcache = fit0@Cache,
    lavimplied = fit0@implied,
    lavh1 = fit0@h1,
    lavoptions = fit0@Options,
    extra = TRUE,
    check.pd = FALSE,
    augmented = FALSE,
    inverted = FALSE
)
meat <- lavInspect(fit0, "information.first.order")
# lavInspect(fit0, "hessian")
# ff0 <- lav_export_estimation(fit0)
# numDeriv::hessian(ff0$objective, coef(fit0), lavaan_model = fit0) -
#     lavInspect(fit0, "hessian")
bread <- lavInspect(fit0, "information.observed")
solve(bread) %*% meat %*% solve(bread)
fit0@vcov$vcov * 75
# May need to consult EFA
var.names <- paste("x", 1:9, sep = "")
# debugonce(lavaan:::lav_model_estimate)  # It appears that EFA also uses optim. So perhaps need to code the objective directly.
fit <- efa(data = HolzingerSwineford1939[, var.names], nfactors = 1:3)
fit$nf3@optim
```

Penalized

```{r}
mod <- "
  ind60 =~ x1 + x2 + x3 + y1 + y2 + y3 + y4
  dem60 =~ x1 + x2 + x3 + y1 + y2 + y3 + y4
  ind60 ~~ ind60
"
fit <- cfa(mod, data = PoliticalDemocracy, std.lv = TRUE, do.fit = FALSE)
```

```{r}
pefa_fit <- penalized_est(
    fit,
    w = .03,
    pen_par_id = 4:10,
    se = "robust.huber.white"
)
summary(pefa_fit)
```

```{r, eval=FALSE}
# Quick simulation to check SEs
set.seed(1234)
R <- 250
est_res <- matrix(NA, nrow = R, ncol = length(coef(pefa_fit)))
se_res <- matrix(NA, nrow = R, ncol = length(coef(pefa_fit)))

# Use the simple structure model as population
pop_model <- parTable(pefa_fit)

for (i in 1:R) {
    # Simulate data
    dat_sim <- simulateData(pop_model, sample.nobs = 200)

    # Fit penalized model
    fit_sim <- cfa(mod, data = dat_sim, std.lv = TRUE, do.fit = FALSE)
    pefa_sim <- try(
        penalized_est(
            fit_sim,
            w = .03,
            pen_par_id = 4:10,
            se = "robust.huber.white"
        ),
        silent = TRUE
    )

    if (!inherits(pefa_sim, "try-error")) {
        est_res[i, ] <- coef(pefa_sim)
        se_res[i, ] <- sqrt(diag(vcov(pefa_sim)))
    }
}

# Compare empirical SD vs mean SE for a few parameters
# (e.g., first few loadings)
res_summary <- data.frame(
    param = names(coef(pefa_fit)),
    emp_sd = apply(est_res, 2, sd, na.rm = TRUE),
    mean_se = apply(se_res, 2, mean, na.rm = TRUE)
)
```

```{r include=FALSE}
# if (!file.exists("sim-se-summary.rds")) {
#     saveRDS(res_summary, "sim-se-summary.rds")
# }
res_summary <- if (file.exists("sim-se-summary.rds")) {
    readRDS("sim-se-summary.rds")
} else {
    data.frame(
        param = names(coef(pefa_fit)),
        emp_sd = NA_real_,
        mean_se = sqrt(diag(vcov(pefa_fit)))
    )
}
```

```{r}
print(res_summary, digits = 2)
```

```{r}
# meat <- lavInspect(pefa_fit, "information.first.order")
# bread <- attr(pefa_fit, "hessian")
# vc_pefa <- solve(bread) %*% meat %*% solve(bread) / 75
# pefa_fit@vcov$vcov <- vc_pefa
# se_pefa <- sqrt(diag(vc_pefa))
# pefa_fit@ParTable$se <- 0 * pefa_fit@ParTable$est
# pefa_fit@ParTable$se[which(pefa_fit@ParTable$free > 0)] <- se_pefa
# cbind(coef(pefa_fit), sqrt(diag(vc_pefa)))
```

## Penalize non-invariance

```{r}
ind_mat <- matrix(
    c("y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8"),
    nrow = 4
)
lconfig_mod_un <- longcfa_syntax(
    ind_mat,
    lv_names = c("dem60", "dem65"),
    lag_cov = TRUE,
    free_latvars = TRUE,
    free_latmeans = TRUE
)
# Specify the under-identified model
lconfig_fit_un <- cfa(
    lconfig_mod_un,
    data = PoliticalDemocracy,
    do.fit = FALSE,
    std.lv = TRUE,
    missing = "fiml",
    estimator = "mlr"
)
ld_id <- get_lav_par_id(lconfig_fit_un, "=~", ind_mat)
int_id <- get_lav_par_id(lconfig_fit_un, "~1", ind_mat)
pen_fit <- penalized_est(
    lconfig_fit_un,
    w = 0.03,
    pen_fn = "l0a",
    pen_diff_id = list(loadings = t(ld_id), intercepts = t(int_id)),
    se = "robust.huber.white"
)
```

Compared to scalar invariance model

```{r}
lscalar_fit <- longcfa(
    ind_mat,
    lv_names = c("dem60", "dem65"),
    data = PoliticalDemocracy,
    lag_cov = TRUE,
    long_equal = c("loadings", "intercepts"),
    se = "robust.huber.white"
)
summary(lscalar_fit)
```